### ISSUE TITLE
FormatCurrency does not work as expected

### ISSUE THREAD

**Issue by robinsandborg** [staccx/bento#4] opened 2020-02-19 11:22 UTC
## The problem
The documentation for formatCurrency is not in line with the expected output. Not sure if the problem is with the documentation or the function.

## Environment

* Bento version (or git revision) that exhibits the issue: d83fa453e2b6025e15ea8396b16c49fa64a9ce17

## Code To Reproduce Issue

The documentation provides this code:
```
<CurrencyText>
   {formatCurrency(100000, {
    symbol: "kr",
    format: "$s  $v",
    suffix: ",-"
  })}
   </CurrencyText>
```

The ouput from this is `kr100 000` from the code example I would expect `kr 100 000,-`

Please share relevant sample code. Or better yet, provide a link to a [minimal reproducible example](https://stackoverflow.com/help/minimal-reproducible-example).

**Comment by XSlemX** [comment] 2020-02-24 08:37
Suffix is not a part of the options if you look at the function. Not a bug. Will change type

**Comment by XSlemX** [comment] 2020-02-24 08:41
I think we might look into removing the accounting dependency. This is pretty simple formatting.

**Comment by XSlemX** [comment] 2020-02-24 08:48
@robinsandborg could you create a spec?

**Comment by XSlemX** [comment] 2020-02-24 08:55
Leaning towards built in features like `Intl.NumberFormat` or `Number.prototype.toLocaleString`. Thoughts?

**Comment by XSlemX** [comment] 2020-02-24 18:01
`formatNumber` and `formatMoney` landed in https://github.com/staccx/bento/commit/0dcb3d601a0bf0ce3eda9d7ea533a6694de79218

**Closed by XSlemX** 2020-02-24 18:01 UTC
Labels: enhancement
